### ISSUE TITLE
Illegal program

### ISSUE THREAD

**Issue by Bobbert23** [paulmillr/scure-btc-signer#36]

**Comment by Bobbert23** [comment]
Can u quit stealing normally you don't rewrite. Programming that's not broken. Are you responsible for missing funds sir ?

**Comment by paulmillr** [comment]
@Bobbert23 I am providing open-source software for free. The software has been through a third-party security audit, checked by other people. It has nothing to do with stealing. You should learn what's GitHub is for instead of writing dumb stuff here.

**Comment by Bobbert23** [comment]
What you just wrote isn't dumb correct? Did you have something to do with my complaint? Were you involved on the team? I didn't even know I had a gift hub account. I found this out less than six months ago and my little angry about it. Yes! Someone has to be accountable and I'm not blaming you. But I don't call you up and call you dumb in a public forum. Maybe you can help me put proper channel should I go through to find out what happened to my missing funds that were taking off a GitHub pay server? I will take all the advice I could get. Thank you.

**Comment by paulmillr** [comment]
Not calling you dumb - just the stuff you've wrote. It's because you don't know how things work here.

Github is a public forum - correct. It hosts 372 million repositories and 100 million users. If you got screwed by one particular project, other 372 million repositories are definitely NOT responsible for it.

> Were you involved on the team.
> GitHub pay server

Which team? Which github pay server? I know about no such things. You did tell nothing about your problem. You need to tell in details what have happened.

What's happening right now can be compared to a dude arriving to a neighborhood and asking a random stranger about his missing funds from 6 months ago. Imagine doing this in the middle of New York. People would just assume you're insane or something.

On the other hand, if you tell "I used project X, from person Y, and I did things A, B and C, and then my money got stolen" - that would definitely be more helpful.
