### ISSUE TITLE
Taproot signing - tapBip32Derivation unsupported

### ISSUE THREAD

**Issue by rolznz** [paulmillr/scure-btc-signer#40]
Hi,

I am trying to sign a simple taproot PSBT transaction generated by sparrow wallet (one input, 2 outputs) and I hit this error:
`if (input.tapBip32Derivation) throw new Error('tapBip32Derivation unsupported');`

Is this planned to be implemented?

Thanks!

**Comment by paulmillr** [comment]
Would be nice to have, but no immediate plans.

**Comment by kyranjamie** [comment]
Is this issue also fixed with https://github.com/paulmillr/scure-btc-signer/issues/101? Would love to see this included in a release.

My use case is that I'm using `bip32Derivation`/`tapBip32Derivation` as a way of passing _which key to use_ metadata when handing off a PSBT to another part of the code to do the signing.

**Comment by paulmillr** [comment]
yeah just need to fix `npm run build`
